jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - script: vcbuild.bat nosign no-cctest release x64 openssl-no-asm
    displayName: 'Build Node'
