pool:
  vmImage: 'vs2017-win2016'

steps:
#- task: CondaEnvironment@1
#  inputs:
#    packageSpecs: 'nasm'
#    installOptions: "-c conda-forge"
#    updateConda: false
#  displayName: Install nasm

- powershell: |
    Get-PSDrive
    $env:temp
    dir $env:temp
  displayName: 'Show free space and temp'
    
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    architecture: 'x64'

- script: |
    vcbuild.bat nosign no-cctest release x64 openssl-no-asm
  displayName: 'Build Node'

- powershell: |
    Get-PSDrive
    $env:temp
    dir $env:temp
  displayName: 'Show free space and temp (post)'
  condition: always()
